USE ROLE ACCOUNTADMIN;
ALTER SESSION SET query_tag = '{"origin":"sf_sit-is","name":"insurance_claims_agent","version":{"major":1,"minor":0},"attributes":{"is_quickstart":1,"source":"sql"}}';

CREATE ROLE IF NOT EXISTS CLAIMS_AGENT_ROLE;
GRANT ROLE CLAIMS_AGENT_ROLE TO ROLE SYSADMIN;

CREATE OR REPLACE DATABASE INSURANCE_CLAIMS_DEMO;

-- Grant all privileges on the database to the role
GRANT ALL ON DATABASE INSURANCE_CLAIMS_DEMO TO ROLE CLAIMS_AGENT_ROLE;

CREATE OR REPLACE SCHEMA INSURANCE_CLAIMS_DEMO.LOSS_CLAIMS;

-- Grant all privileges on the schema to the role
GRANT ALL ON SCHEMA INSURANCE_CLAIMS_DEMO.LOSS_CLAIMS TO ROLE CLAIMS_AGENT_ROLE;

-- snowflake intelligence setup
CREATE SNOWFLAKE INTELLIGENCE IF NOT EXISTS SNOWFLAKE_INTELLIGENCE_OBJECT_DEFAULT;
GRANT CREATE SNOWFLAKE INTELLIGENCE ON ACCOUNT TO ROLE CLAIMS_AGENT_ROLE;
GRANT USAGE ON SNOWFLAKE INTELLIGENCE SNOWFLAKE_INTELLIGENCE_OBJECT_DEFAULT TO ROLE CLAIMS_AGENT_ROLE;
GRANT MODIFY ON SNOWFLAKE INTELLIGENCE SNOWFLAKE_INTELLIGENCE_OBJECT_DEFAULT TO ROLE CLAIMS_AGENT_ROLE;
GRANT USAGE ON SNOWFLAKE INTELLIGENCE SNOWFLAKE_INTELLIGENCE_OBJECT_DEFAULT TO ROLE PUBLIC;
GRANT CREATE AGENT ON SCHEMA INSURANCE_CLAIMS_DEMO.LOSS_CLAIMS TO ROLE CLAIMS_AGENT_ROLE;

-- Create custom warehouse for claims processing
CREATE WAREHOUSE IF NOT EXISTS CLAIMS_AGENT_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 300
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Warehouse for claims agent operations';

-- Grant warehouse privileges to the role
GRANT USAGE ON WAREHOUSE CLAIMS_AGENT_WH TO ROLE CLAIMS_AGENT_ROLE;
GRANT OPERATE ON WAREHOUSE CLAIMS_AGENT_WH TO ROLE CLAIMS_AGENT_ROLE;
GRANT MODIFY ON WAREHOUSE CLAIMS_AGENT_WH TO ROLE CLAIMS_AGENT_ROLE;

-- Switch to custom role for setup
USE ROLE CLAIMS_AGENT_ROLE;
USE DATABASE INSURANCE_CLAIMS_DEMO;
USE SCHEMA LOSS_CLAIMS;
USE WAREHOUSE CLAIMS_AGENT_WH;

CREATE OR REPLACE STAGE INSURANCE_CLAIMS_DEMO.LOSS_CLAIMS.LOSS_EVIDENCE 
	DIRECTORY = ( ENABLE = true ) 
	ENCRYPTION = ( TYPE = 'SNOWFLAKE_SSE' );

-- create tables

CREATE OR REPLACE TABLE CLAIMS (
    CLAIM_NO VARCHAR,
    LINE_OF_BUSINESS VARCHAR,
    CLAIM_STATUS VARCHAR,
    CAUSE_OF_LOSS VARCHAR,
    CREATED_DATE DATE,
    LOSS_DATE DATE,
    REPORTED_DATE DATE,
    CLAIMANT_ID VARCHAR,
    PERFORMER VARCHAR,
    POLICY_NO VARCHAR,
    FNOL_COMPLETION_DATE DATE,
    LOSS_DESCRIPTION VARCHAR,
    LOSS_STATE VARCHAR,
    LOSS_ZIP_CODE VARCHAR
);

CREATE OR REPLACE TABLE CLAIM_LINES (
    CLAIM_NO VARCHAR,
    LINE_NO INT,
    LOSS_DESCRIPTION VARCHAR,
    CLAIM_STATUS VARCHAR,
    CREATED_DATE DATE,
    REPORTED_DATE DATE,
    CLAIMANT_ID VARCHAR,
    PERFORMER_ID VARCHAR
);

CREATE OR REPLACE TABLE FINANCIAL_TRANSACTIONS (
    FXID VARCHAR,
    LINE_NO INT,
    FINANCIAL_TYPE VARCHAR,
    CURRENCY VARCHAR,
    FIN_TX_AMT DECIMAL(18, 2),
    FIN_TX_POST_DT DATE
);

CREATE OR REPLACE TABLE AUTHORIZATION (
    PERFORMER_ID VARCHAR(50) PRIMARY KEY,
    FROM_AMT DECIMAL(18, 2),
    TO_AMT DECIMAL(18, 2),
    CURRENCY VARCHAR(10)
);

CREATE OR REPLACE TABLE INVOICES (
    INV_ID VARCHAR,
    INV_LINE_NBR VARCHAR,
    LINE_NO VARCHAR,
    DESCRIPTION VARCHAR,
    CURRENCY VARCHAR(10),
    INVOICE_AMOUNT DECIMAL(18, 2),
    INVOICE_DATE DATE,
    VENDOR VARCHAR
);

INSERT INTO CLAIMS (
    CLAIM_NO, LINE_OF_BUSINESS, CLAIM_STATUS, CAUSE_OF_LOSS,
    CREATED_DATE, LOSS_DATE, REPORTED_DATE, CLAIMANT_ID, PERFORMER,
    POLICY_NO, FNOL_COMPLETION_DATE, LOSS_DESCRIPTION, LOSS_STATE, LOSS_ZIP_CODE
) VALUES
('1899', 'Property', 'Open', 'Hurricane', '2025-01-06', '2025-01-06', '2025-01-06', '19', '18',
 '888', '01/06/2025', 'Damaged dwelling and fence after the tree fell', 'NJ', '8820');


INSERT INTO CLAIM_LINES (
    CLAIM_NO, LINE_NO, LOSS_DESCRIPTION, CLAIM_STATUS,
    CREATED_DATE, REPORTED_DATE, CLAIMANT_ID, PERFORMER_ID
) VALUES
('1899', 16, 'Damaged Dwelling', 'Open', '2025-01-06', '2025-01-06', '19', '171'),
('1899', 17, 'Damaged Fence', 'Open', '2025-01-06', '2025-01-06', '19', '181'),
('1899', 18, 'Damaged Lawn', 'Open', '2025-01-06', '2025-01-06', '19', '191');

INSERT INTO FINANCIAL_TRANSACTIONS (
    FXID, LINE_NO, FINANCIAL_TYPE, CURRENCY, FIN_TX_AMT, FIN_TX_POST_DT
) VALUES
('21', 16, 'RSV', 'USD', 4000.00, '2025-02-15'), 
('22', 16, 'PAY', 'USD', 4000.00, '2025-06-15'), -- Mapped to Line 18 (Damaged Dwelling)
('23', 17, 'RSV', 'USD', 3000.00, '2025-03-06'), -- Mapped to Line 19 (Damaged Fence)
('24', 17, 'PAY', 'USD', 3500.00, '2025-05-05'), -- Mapped to Line 19 (Damaged Fence)
('25', 18, 'RSV', 'USD', 2000.00, '2025-02-15'), -- Mapped to Line 20 (Damaged Lawn)
('26', 18, 'PAY', 'USD', 2000.00, '2025-04-05'); -- Mapped to Line 20 (Damaged Lawn);

INSERT INTO AUTHORIZATION (PERFORMER_ID, FROM_AMT, TO_AMT, CURRENCY) VALUES
('171', 0.00, 5000.00, 'USD'),
('181', 0.00, 3000.00, 'USD'),
('191', 0.00, 2500.00, 'USD');

INSERT INTO INVOICES (INV_ID, INV_LINE_NBR, LINE_NO, DESCRIPTION, CURRENCY, INVOICE_AMOUNT, INVOICE_DATE, VENDOR) VALUES
('5', 1, 16, 'Wooden Logs', 'USD', 2500.00, '2025-05-15', 'ABC'),
('5', 2, 16, 'Hardware', 'USD', 1000.00, '2025-05-15', 'ABC'),
('5', 3, 16, 'Labor', 'USD', 500.00, '2025-05-15', 'ABC'),
('6', 1, 17, 'Fence', 'USD', 3000.00, '2025-04-20', 'LMN'),
('6', 2, 17, 'Labor', 'USD', 500.00, '2025-04-20', 'LMN'),
('7', 1, 18, 'Lawn', 'USD', 1200.00, '2025-03-18', 'XYZ'),
('7', 2, 18, 'Equipment Rental', 'USD', 200.00, '2025-03-18', 'XYZ'),
('7', 3, 18, 'Labor', 'USD', 600.00, '2025-03-18', 'XYZ');

--upload files to loss_evidence stage